services:
  reformat:
    build:
      context: ..
      dockerfile: reformat/Dockerfile
    container_name: reformat-code
    volumes:
      - ./<MODULE_NAME>/src:/workspace/src:rw
    working_dir: /workspace
    network_mode: bridge
