services:
  docs-validator:
    build:
      context: ..
      dockerfile: docs-validate/Dockerfile
    image: <MODULE-NAME>-docs-validate:latest
    working_dir: /workspace
    volumes:
      - ../:/workspace
    command: mkdocs build --strict
